# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Damiaa_Wandel_App_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Damiaa_Wandel_App_iOS

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add the Firebase pod for Authentication
pod 'Firebase/Auth'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
